# Generated by Django 3.2.6 on 2022-07-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='заголовок')),
                ('text', models.TextField(max_length=5000, verbose_name='контент')),
            ],
        ),
    ]
