# Generated by Django 3.2.6 on 2022-07-06 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_comments_name_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='name_art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article'),
        ),
    ]
